export const VERSES = [
  ["Psalm 37:23-24","The LORD makes firm the steps of the one who delights in him; though he may stumble, he will not fall, for the LORD upholds him with his hand."],
  ["James 4:8","Come near to God and he will come near to you."],
  ["Psalm 112:7","They will have no fear of bad news; their hearts are steadfast, trusting in the LORD."],
  ["Luke 23:34","Jesus said, 'Father, forgive them, for they do not know what they are doing.'"],
  ["Psalm 143:8","Let the morning bring me word of your unfailing love, for I have put my trust in you. Show me the way I should go, for to you I entrust my life."],
  ["Matthew 5:4","Blessed are those who mourn, for they will be comforted."],
  ["Proverbs 3:5-6","Trust in the LORD with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight."],
  ["Hebrews 10:23","Let us hold unswervingly to the hope we profess, for he who promised is faithful."],
  ["Proverbs 2:6","For the LORD gives wisdom; from his mouth come knowledge and understanding."],
  ["James 5:16","Therefore confess your sins to each other and pray for each other so that you may be healed. The prayer of a righteous person is powerful and effective."],
  ["Isaiah 61:3","To bestow on them a crown of beauty instead of ashes, the oil of joy instead of mourning, and a garment of praise instead of a spirit of despair."],
  ["Matthew 6:34","Therefore do not worry about tomorrow, for tomorrow will worry about itself. Each day has enough trouble of its own."],
  ["Isaiah 53:6","We all, like sheep, have gone astray, each of us has turned to our own way; and the LORD has laid on him the iniquity of us all."],
  ["Romans 6:23","For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord."],
  ["Psalm 23:4","Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me."],
  ["Matthew 7:7-8","Ask and it will be given to you; seek and you will find; knock and the door will be opened to you. For everyone who asks receives; the one who seeks finds."],
  ["Ephesians 3:20","Now to him who is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us."],
  ["Psalm 23:1","The LORD is my shepherd, I lack nothing."],
  ["Acts 2:42","They devoted themselves to the apostles' teaching and to fellowship, to the breaking of bread and to prayer."],
  ["Exodus 15:2","The LORD is my strength and my defense; he has become my salvation. He is my God, and I will praise him, my father's God, and I will exalt him."],
  ["Matthew 5:5","Blessed are the meek, for they will inherit the earth."],
  ["Jeremiah 32:17","Ah, Sovereign LORD, you have made the heavens and the earth by your great power and outstretched arm. Nothing is too hard for you."],
  ["1 John 4:8","Whoever does not love does not know God, because God is love."],
  ["Lamentations 3:22-23","Because of the LORD's great love we are not consumed, for his compassions never fail. They are new every morning; great is your faithfulness."],
  ["Luke 1:37","For no word from God will ever fail."],
  ["Psalm 86:5","You, Lord, are forgiving and good, abounding in love to all who call to you."],
  ["James 1:5","If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault, and it will be given to you."],
  ["Psalm 119:11","I have hidden your word in my heart that I might not sin against you."],
  ["1 Peter 1:3","Praise be to the God and Father of our Lord Jesus Christ! In his great mercy he has given us new birth into a living hope through the resurrection of Jesus Christ from the dead."],
  ["Psalm 63:1","You, God, are my God, earnestly I seek you; I thirst for you, my whole being longs for you, in a dry and parched land where there is no water."],
  ["Matthew 11:28-29","Come to me, all you who are weary and burdened, and I will give you rest. Take my yoke upon you and learn from me, for I am gentle and humble in heart, and you will find rest for your souls."],
  ["Hebrews 11:6","And without faith it is impossible to please God, because anyone who comes to him must believe that he exists and that he rewards those who earnestly seek him."],
  ["Isaiah 40:8","The grass withers and the flowers fall, but the word of our God endures forever."],
  ["Luke 9:23","Then he said to them all: 'Whoever wants to be my disciple must deny themselves and take up their cross daily and follow me.'"],
  ["Psalm 84:11","For the LORD God is a sun and shield; the LORD bestows favor and honor; no good thing does he withhold from those whose walk is blameless."],
  ["Philippians 4:13","I can do all this through him who gives me strength."],
  ["Ecclesiastes 12:13","Fear God and keep his commandments, for this is the duty of all mankind."],
  ["John 1:12","Yet to all who did receive him, to those who believed in his name, he gave the right to become children of God."],
  ["Psalm 118:6","The LORD is with me; I will not be afraid. What can mere mortals do to me?"],
  ["Matthew 5:7","Blessed are the merciful, for they will be shown mercy."],
  ["Psalm 71:5","For you have been my hope, Sovereign LORD, my confidence since my youth."],
  ["John 8:36","So if the Son sets you free, you will be free indeed."],
  ["Genesis 50:20","You intended to harm me, but God intended it for good to accomplish what is now being done, the saving of many lives."],
  ["1 Corinthians 15:10","But by the grace of God I am what I am, and his grace to me was not without effect."],
  ["Jeremiah 17:7-8","But blessed is the one who trusts in the LORD, whose confidence is in him. They will be like a tree planted by the water that sends out its roots by the stream."],
  ["Romans 8:1","Therefore, there is now no condemnation for those who are in Christ Jesus."],
  ["Psalm 37:4","Take delight in the LORD, and he will give you the desires of your heart."],
  ["John 16:33","I have told you these things, so that in me you may have peace. In this world you will have trouble. But take heart! I have overcome the world."],
  ["Romans 1:16","For I am not ashamed of the gospel, because it is the power of God that brings salvation to everyone who believes."],
  ["Psalm 4:8","In peace I will lie down and sleep, for you alone, LORD, make me dwell in safety."],
  ["Luke 11:9","So I say to you: Ask and it will be given to you; seek and you will find; knock and the door will be opened to you."],
  ["Psalm 19:1","The heavens declare the glory of God; the skies proclaim the work of his hands."],
  ["Ephesians 6:10","Finally, be strong in the Lord and in his mighty power."],
  ["Psalm 16:11","You make known to me the path of life; you will fill me with joy in your presence, with eternal pleasures at your right hand."],
  ["Philippians 4:4","Rejoice in the Lord always. I will say it again: Rejoice!"],
  ["Psalm 16:8","I keep my eyes always on the LORD. With him at my right hand, I will not be shaken."],
  ["Galatians 6:9","Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up."],
  ["Jeremiah 29:13","You will seek me and find me when you seek me with all your heart."],
  ["Hebrews 12:1-2","Therefore, since we are surrounded by such a great cloud of witnesses, let us throw off everything that hinders and the sin that so easily entangles. And let us run with perseverance the race marked out for us, fixing our eyes on Jesus."],
  ["Proverbs 22:6","Start children off on the way they should go, and even when they are old they will not turn from it."],
  ["John 20:29","Then Jesus told him, 'Because you have seen me, you have believed; blessed are those who have not seen and yet have believed.'"],
  ["Exodus 33:14","The LORD replied, 'My Presence will go with you, and I will give you rest.'"],
  ["Ephesians 6:11","Put on the full armor of God, so that you can take your stand against the devil's schemes."],
  ["2 Timothy 4:7","I have fought the good fight, I have finished the race, I have kept the faith."],
  ["Psalm 29:11","The LORD gives strength to his people; the LORD blesses his people with peace."],
  ["Luke 2:10-11","But the angel said to them, 'Do not be afraid. I bring you good news that will cause great joy for all the people. Today in the town of David a Savior has been born to you; he is the Messiah, the Lord.'"],
  ["Job 23:10","But he knows the way that I take; when he has tested me, I will come forth as gold."],
  ["John 8:32","Then you will know the truth, and the truth will set you free."],
  ["Psalm 27:14","Wait for the LORD; be strong and take heart and wait for the LORD."],
  ["Revelation 3:20","Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in and eat with that person, and they with me."],
  ["Daniel 6:26-27","He is the living God and he endures forever; his kingdom will not be destroyed, his dominion will never end. He rescues and he saves; he performs signs and wonders in the heavens and on the earth."],
  ["1 Thessalonians 5:16-18","Rejoice always, pray continually, give thanks in all circumstances; for this is God's will for you in Christ Jesus."],
  ["Proverbs 28:13","Whoever conceals their sins does not prosper, but the one who confesses and renounces them finds mercy."],
  ["Matthew 6:25","Therefore I tell you, do not worry about your life, what you will eat or drink; or about your body, what you will wear. Is not life more than food, and the body more than clothes?"],
  ["Psalm 56:3","When I am afraid, I put my trust in you."],
  ["John 14:15","If you love me, keep my commands."],
  ["Genesis 28:15","I am with you and will watch over you wherever you go, and I will bring you back to this land. I will not leave you until I have done what I have promised you."],
  ["Romans 8:37-39","No, in all these things we are more than conquerors through him who loved us. For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers, neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God that is in Christ Jesus our Lord."],
  ["Psalm 8:1","LORD, our Lord, how majestic is your name in all the earth! You have set your glory in the heavens."],
  ["Philippians 1:6","Being confident of this, that he who began a good work in you will carry it on to completion until the day of Christ Jesus."],
  ["Galatians 5:22-23","But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control."],
  ["Nahum 1:7","The LORD is good, a refuge in times of trouble. He cares for those who trust in him."],
  ["1 Corinthians 13:13","And now these three remain: faith, hope and love. But the greatest of these is love."],
  ["Psalm 91:1-2","Whoever dwells in the shelter of the Most High will rest in the shadow of the Almighty. I will say of the LORD, 'He is my refuge and my fortress, my God, in whom I trust.'"],
  ["Revelation 21:4","He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain, for the old order of things has passed away."],
  ["Psalm 34:4","I sought the LORD, and he answered me; he delivered me from all my fears."],
  ["2 Corinthians 12:9","But he said to me, 'My grace is sufficient for you, for my power is made perfect in weakness.'"],
  ["Proverbs 19:21","Many are the plans in a person's heart, but it is the LORD's purpose that prevails."],
  ["Colossians 3:23","Whatever you do, work at it with all your heart, as working for the Lord, not for human masters."],
  ["Psalm 34:18","The LORD is close to the brokenhearted and saves those who are crushed in spirit."],
  ["1 Corinthians 13:7","It always protects, always trusts, always hopes, always perseveres."],
  ["Psalm 145:18","The LORD is near to all who call on him, to all who call on him in truth."],
  ["Romans 12:10","Be devoted to one another in love. Honor one another above yourselves."],
  ["2 Chronicles 7:14","If my people, who are called by my name, will humble themselves and pray and seek my face and turn from their wicked ways, then I will hear from heaven, and I will forgive their sin and will heal their land."],
  ["John 14:27","Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid."],
  ["Matthew 4:4","Jesus answered, 'It is written: Man shall not live on bread alone, but on every word that comes from the mouth of God.'"],
  ["Isaiah 48:17","I am the LORD your God, who teaches you what is best for you, who directs you in the way you should go."],
  ["Jude 1:24-25","To him who is able to keep you from stumbling and to present you before his glorious presence without fault and with great joy — to the only God our Savior be glory, majesty, power and authority, through Jesus Christ our Lord."],
  ["Isaiah 60:1","Arise, shine, for your light has come, and the glory of the LORD rises upon you."],
  ["Matthew 17:20","Truly I tell you, if you have faith as small as a mustard seed, you can say to this mountain, 'Move from here to there,' and it will move. Nothing will be impossible for you."],
  ["Genesis 12:2","I will make you into a great nation, and I will bless you; I will make your name great, and you will be a blessing."],
  ["Romans 5:3-4","Not only so, but we also glory in our sufferings, because we know that suffering produces perseverance; perseverance, character; and character, hope."],
  ["Psalm 103:12","As far as the east is from the west, so far has he removed our transgressions from us."],
  ["Philippians 4:8","Finally, brothers and sisters, whatever is true, whatever is noble, whatever is right, whatever is pure, whatever is lovely, whatever is admirable — if anything is excellent or praiseworthy — think about such things."],
  ["Proverbs 11:25","A generous person will prosper; whoever refreshes others will be refreshed."],
  ["Hebrews 13:8","Jesus Christ is the same yesterday and today and forever."],
  ["Isaiah 55:11","So is my word that goes out from my mouth: It will not return to me empty, but will accomplish what I desire and achieve the purpose for which I sent it."],
  ["Revelation 1:8","'I am the Alpha and the Omega,' says the Lord God, 'who is, and who was, and who is to come, the Almighty.'"],
  ["Psalm 139:1-2","You have searched me, LORD, and you know me. You know when I sit and when I rise; you perceive my thoughts from afar."],
  ["1 John 4:7","Dear friends, let us love one another, for love comes from God. Everyone who loves has been born of God and knows God."],
  ["Ecclesiastes 3:1","There is a time for everything, and a season for every activity under the heavens."],
  ["1 Peter 3:15","But in your hearts revere Christ as Lord. Always be prepared to give an answer to everyone who asks you to give the reason for the hope that you have."],
  ["Luke 12:7","Indeed, the very hairs of your head are all numbered. Don't be afraid; you are worth more than many sparrows."],
  ["Psalm 32:8","I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you."],
  ["2 Corinthians 1:3-4","Praise be to the God and Father of our Lord Jesus Christ, the Father of compassion and the God of all comfort, who comforts us in all our troubles."],
  ["Proverbs 16:9","In their hearts humans plan their course, but the LORD establishes their steps."],
  ["John 1:1","In the beginning was the Word, and the Word was with God, and the Word was God."],
  ["1 Chronicles 29:11","Yours, LORD, is the greatness and the power and the glory and the majesty and the splendor, for everything in heaven and earth is yours."],
  ["Ephesians 4:32","Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you."],
  ["Psalm 94:19","When anxiety was great within me, your consolation brought me joy."],
  ["2 Corinthians 5:21","God made him who had no sin to be sin for us, so that in him we might become the righteousness of God."],
  ["Isaiah 53:5","But he was pierced for our transgressions, he was crushed for our iniquities; the punishment that brought us peace was on him, and by his wounds we are healed."],
  ["Matthew 22:37-39","Jesus replied: 'Love the Lord your God with all your heart and with all your soul and with all your mind. This is the first and greatest commandment. And the second is like it: Love your neighbor as yourself.'"],
  ["1 Kings 8:56","Praise be to the LORD, who has given rest to his people Israel just as he promised. Not one word has failed of all the good promises he gave through his servant Moses."],
  ["Matthew 7:12","So in everything, do to others what you would have them do to you, for this sums up the Law and the Prophets."],
  ["Psalm 119:105","Your word is a lamp for my feet, a light on my path."],
  ["1 Peter 4:8","Above all, love each other deeply, because love covers over a multitude of sins."],
  ["Colossians 3:15","Let the peace of Christ rule in your hearts, since as members of one body you were called to peace. And be thankful."],
  ["Proverbs 17:17","A friend loves at all times, and a brother is born for a time of adversity."],
  ["Hebrews 11:1","Now faith is confidence in what we hope for and assurance about what we do not see."],
  ["Proverbs 29:25","Fear of man will prove to be a snare, but whoever trusts in the LORD is kept safe."],
  ["John 17:17","Sanctify them by the truth; your word is truth."],
  ["Psalm 130:5","I wait for the LORD, my whole being waits, and in his word I put my hope."],
  ["Romans 8:18","I consider that our present sufferings are not worth comparing with the glory that will be revealed in us."],
  ["Psalm 20:7","Some trust in chariots and some in horses, but we trust in the name of the LORD our God."],
  ["1 Corinthians 15:57","But thanks be to God! He gives us the victory through our Lord Jesus Christ."],
  ["Psalm 27:4","One thing I ask from the LORD, this only do I seek: that I may dwell in the house of the LORD all the days of my life."],
  ["John 3:16","For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life."],
  ["Nehemiah 8:10","Do not grieve, for the joy of the LORD is your strength."],
  ["1 Corinthians 1:18","For the message of the cross is foolishness to those who are perishing, but to us who are being saved it is the power of God."],
  ["Psalm 107:1","Give thanks to the LORD, for he is good; his love endures forever."],
  ["John 10:10","The thief comes only to steal and kill and destroy; I have come that they may have life, and have it to the full."],
  ["Colossians 3:1-2","Since, then, you have been raised with Christ, set your hearts on things above, where Christ is, seated at the right hand of God. Set your minds on things above, not on earthly things."],
  ["Psalm 118:24","The LORD has done it this very day; let us rejoice today and be glad."],
  ["2 Corinthians 4:16-17","Therefore we do not lose heart. Though outwardly we are wasting away, yet inwardly we are being renewed day by day. For our light and momentary troubles are achieving for us an eternal glory that far outweighs them all."],
  ["Ecclesiastes 4:9-10","Two are better than one, because they have a good return for their labor: If either of them falls down, one can help the other up."],
  ["Galatians 2:20","I have been crucified with Christ and I no longer live, but Christ lives in me. The life I now live in the body, I live by faith in the Son of God, who loved me and gave himself for me."],
  ["Ecclesiastes 3:11","He has made everything beautiful in its time. He has also set eternity in the human heart; yet no one can fathom what God has done from beginning to end."],
  ["1 Corinthians 16:13-14","Be on your guard; stand firm in the faith; be courageous; be strong. Do everything in love."],
  ["Psalm 24:1","The earth is the LORD's, and everything in it, the world, and all who live in it."],
  ["2 Corinthians 9:6-7","Remember this: Whoever sows sparingly will also reap sparingly, and whoever sows generously will also reap generously. Each of you should give what you have decided in your heart to give, not reluctantly or under compulsion, for God loves a cheerful giver."],
  ["Psalm 116:1-2","I love the LORD, for he heard my voice; he heard my cry for mercy. Because he turned his ear to me, I will call on him as long as I live."],
  ["2 Timothy 1:7","For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline."],
  ["Psalm 118:14","The LORD is my strength and my defense; he has become my salvation."],
  ["Luke 6:27-28","But to you who are listening I say: Love your enemies, do good to those who hate you, bless those who curse you, pray for those who mistreat you."],
  ["Deuteronomy 6:5","Love the LORD your God with all your heart and with all your soul and with all your strength."],
  ["Matthew 19:26","Jesus looked at them and said, 'With man this is impossible, but with God all things are possible.'"],
  ["Deuteronomy 29:29","The secret things belong to the LORD our God, but the things revealed belong to us and to our children forever."],
  ["Colossians 3:12","Therefore, as God's chosen people, holy and dearly loved, clothe yourselves with compassion, kindness, humility, gentleness and patience."],
  ["2 Timothy 2:15","Do your best to present yourself to God as one approved, a worker who does not need to be ashamed and who correctly handles the word of truth."],
  ["Isaiah 58:11","The LORD will guide you always; he will satisfy your needs in a sun-scorched land and will strengthen your frame."],
  ["1 Peter 2:9","But you are a chosen people, a royal priesthood, a holy nation, God's special possession, that you may declare the praises of him who called you out of darkness into his wonderful light."],
  ["Joshua 1:9","Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged, for the LORD your God will be with you wherever you go."],
  ["John 15:13","Greater love has no one than this: to lay down one's life for one's friends."],
  ["Isaiah 9:6","For to us a child is born, to us a son is given, and the government will be on his shoulders. And he will be called Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace."],
  ["Romans 8:31","What, then, shall we say in response to these things? If God is for us, who can be against us?"],
  ["Psalm 127:1","Unless the LORD builds the house, the builders labor in vain."],
  ["James 1:22","Do not merely listen to the word, and so deceive yourselves. Do what it says."],
  ["Psalm 145:8","The LORD is gracious and compassionate, slow to anger and rich in love."],
  ["1 Corinthians 2:9","However, as it is written: 'What no eye has seen, what no ear has heard, and what no human mind has conceived — the things God has prepared for those who love him.'"],
  ["Habakkuk 3:17-18","Though the fig tree does not bud and there are no grapes on the vines, though the olive crop fails and the fields produce no food — yet I will rejoice in the LORD, I will be joyful in God my Savior."],
  ["Acts 17:28","For in him we live and move and have our being."],
  ["Isaiah 46:4","Even to your old age and gray hairs I am he, I am he who will sustain you. I have made you and I will carry you; I will sustain you and I will rescue you."],
  ["Mark 10:45","For even the Son of Man did not come to be served, but to serve, and to give his life as a ransom for many."],
  ["1 John 3:16","This is how we know what love is: Jesus Christ laid down his life for us. And we ought to lay down our lives for our brothers and sisters."],
  ["Zechariah 4:6","Not by might nor by power, but by my Spirit, says the LORD Almighty."],
  ["2 Corinthians 4:18","So we fix our eyes not on what is seen, but on what is unseen, since what is seen is temporary, but what is unseen is eternal."],
  ["Isaiah 41:13","For I am the LORD your God who takes hold of your right hand and says to you, Do not fear; I will help you."],
  ["John 8:12","When Jesus spoke again to the people, he said, 'I am the light of the world. Whoever follows me will never walk in darkness, but will have the light of life.'"],
  ["Psalm 103:2-3","Praise the LORD, my soul, and forget not all his benefits — who forgives all your sins and heals all your diseases."],
  ["James 1:2-3","Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds, because you know that the testing of your faith produces perseverance."],
  ["Psalm 18:2","The LORD is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge, my shield and the horn of my salvation, my stronghold."],
  ["Matthew 5:6","Blessed are those who hunger and thirst for righteousness, for they will be filled."],
  ["Isaiah 41:10","So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand."],
  ["Mark 12:30-31","Love the Lord your God with all your heart and with all your soul and with all your mind and with all your strength. The second is this: Love your neighbor as yourself."],
  ["Isaiah 43:1-2","Do not fear, for I have redeemed you; I have summoned you by name; you are mine. When you pass through the waters, I will be with you; and when you pass through the rivers, they will not sweep over you."],
  ["1 John 3:1","See what great love the Father has lavished on us, that we should be called children of God! And that is what we are!"],
  ["Psalm 121:7-8","The LORD will keep you from all harm — he will watch over your life; the LORD will watch over your coming and going both now and forevermore."],
  ["1 Corinthians 13:4-5","Love is patient, love is kind. It does not envy, it does not boast, it is not proud. It does not dishonor others, it is not self-seeking, it is not easily angered, it keeps no record of wrongs."],
  ["Exodus 14:14","The LORD will fight for you; you need only to be still."],
  ["Luke 19:10","For the Son of Man came to seek and to save the lost."],
  ["Ephesians 2:8-9","For it is by grace you have been saved, through faith — and this is not from yourselves, it is the gift of God — not by works, so that no one can boast."],
  ["2 Chronicles 20:15","Do not be afraid or discouraged because of this vast army. For the battle is not yours, but God's."],
  ["Revelation 22:13","I am the Alpha and the Omega, the First and the Last, the Beginning and the End."],
  ["Zephaniah 3:17","The LORD your God is with you, the Mighty Warrior who saves. He will take great delight in you; in his love he will no longer rebuke you, but will rejoice over you with singing."],
  ["1 Peter 5:8","Be sober-minded; be watchful. Your adversary the devil prowls around like a roaring lion, seeking someone to devour."],
  ["Psalm 91:11","For he will command his angels concerning you to guard you in all your ways."],
  ["Titus 3:4-5","But when the kindness and love of God our Savior appeared, he saved us, not because of righteous things we had done, but because of his mercy."],
  ["Deuteronomy 31:8","The LORD himself goes before you and will be with you; he will never leave you nor forsake you. Do not be afraid; do not be discouraged."],
  ["James 2:17","In the same way, faith by itself, if it is not accompanied by action, is dead."],
  ["Psalm 30:5","Weeping may stay for the night, but rejoicing comes in the morning."],
  ["Ephesians 4:2-3","Be completely humble and gentle; be patient, bearing with one another in love. Make every effort to keep the unity of the Spirit through the bond of peace."],
  ["Psalm 37:5","Commit your way to the LORD; trust in him and he will do this."],
  ["John 4:24","God is spirit, and his worshipers must worship in the Spirit and in truth."],
  ["Genesis 1:1","In the beginning God created the heavens and the earth."],
  ["Philippians 4:19","And my God will meet all your needs according to the riches of his glory in Christ Jesus."],
  ["Philippians 2:3-4","Do nothing out of selfish ambition or vain conceit. Rather, in humility value others above yourselves, not looking to your own interests but each of you to the interests of the others."],
  ["Psalm 119:130","The unfolding of your words gives light; it gives understanding to the simple."],
  ["1 Timothy 6:6","But godliness with contentment is great gain."],
  ["Psalm 27:1","The LORD is my light and my salvation — whom shall I fear? The LORD is the stronghold of my life — of whom shall I be afraid?"],
  ["Philippians 3:13-14","But one thing I do: Forgetting what is behind and straining toward what is ahead, I press on toward the goal to win the prize for which God has called me heavenward in Christ Jesus."],
  ["Joshua 1:8","Keep this Book of the Law always on your lips; meditate on it day and night, so that you may be careful to do everything written in it. Then you will be prosperous and successful."],
  ["Acts 2:38","Peter replied, 'Repent and be baptized, every one of you, in the name of Jesus Christ for the forgiveness of your sins. And you will receive the gift of the Holy Spirit.'"],
  ["Numbers 23:19","God is not human, that he should lie, not a human being, that he should change his mind. Does he speak and then not act? Does he promise and not fulfill?"],
  ["Matthew 25:40","The King will reply, 'Truly I tell you, whatever you did for one of the least of these brothers and sisters of mine, you did for me.'"],
  ["Jeremiah 29:11","For I know the plans I have for you, declares the LORD, plans to prosper you and not to harm you, plans to give you hope and a future."],
  ["Romans 8:26","In the same way, the Spirit helps us in our weakness. We do not know what we ought to pray for, but the Spirit himself intercedes for us through wordless groans."],
  ["Joel 2:28","And afterward, I will pour out my Spirit on all people. Your sons and daughters will prophesy, your old men will dream dreams, your young men will see visions."],
  ["Romans 5:8","But God demonstrates his own love for us in this: While we were still sinners, Christ died for us."],
  ["Isaiah 64:4","Since ancient times no one has heard, no ear has perceived, no eye has seen any God besides you, who acts on behalf of those who wait for him."],
  ["Matthew 5:16","In the same way, let your light shine before others, that they may see your good deeds and glorify your Father in heaven."],
  ["Psalm 46:1","God is our refuge and strength, an ever-present help in trouble."],
  ["Romans 8:28","And we know that in all things God works for the good of those who love him, who have been called according to his purpose."],
  ["Hebrews 13:5","Keep your lives free from the love of money and be content with what you have, because God has said, 'Never will I leave you; never will I forsake you.'"],
  ["Proverbs 18:24","One who has unreliable friends soon comes to ruin, but there is a friend who sticks closer than a brother."],
  ["Ephesians 2:10","For we are God's handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do."],
  ["Psalm 139:16","Your eyes saw my unformed body; all the days ordained for me were written in your book before one of them came to be."],
  ["Romans 12:2","Do not conform to the pattern of this world, but be transformed by the renewing of your mind."],
  ["Psalm 73:26","My flesh and my heart may fail, but God is the strength of my heart and my portion forever."],
  ["Luke 6:31","Do to others as you would have them do to you."],
  ["Jeremiah 33:3","Call to me and I will answer you and tell you great and unsearchable things you do not know."],
  ["Romans 10:9","If you declare with your mouth, 'Jesus is Lord,' and believe in your heart that God raised him from the dead, you will be saved."],
  ["Genesis 2:24","That is why a man leaves his father and mother and is united to his wife, and they become one flesh."],
  ["1 John 4:19","We love because he first loved us."],
  ["Deuteronomy 8:3","Man does not live on bread alone but on every word that comes from the mouth of the LORD."],
  ["John 1:14","The Word became flesh and made his dwelling among us. We have seen his glory, the glory of the one and only Son, who came from the Father, full of grace and truth."],
  ["Genesis 15:6","Abram believed the LORD, and he credited it to him as righteousness."],
  ["John 3:17","For God did not send his Son into the world to condemn the world, but to save the world through him."],
  ["Colossians 1:16-17","For in him all things were created: things in heaven and on earth, visible and invisible. He is before all things, and in him all things hold together."],
  ["Isaiah 6:8","Then I heard the voice of the Lord saying, 'Whom shall I send? And who will go for us?' And I said, 'Here am I. Send me!'"],
  ["Romans 15:13","May the God of hope fill you with all joy and peace as you trust in him, so that you may overflow with hope by the power of the Holy Spirit."],
  ["Psalm 138:8","The LORD will vindicate me; your love, LORD, endures forever — do not abandon the works of your hands."],
  ["Ephesians 1:3","Praise be to the God and Father of our Lord Jesus Christ, who has blessed us in the heavenly realms with every spiritual blessing in Christ."],
  ["2 Samuel 22:31","As for God, his way is perfect: The LORD's word is flawless; he shields all who take refuge in him."],
  ["Hebrews 12:11","No discipline seems pleasant at the time, but painful. Later on, however, it produces a harvest of righteousness and peace for those who have been trained by it."],
  ["Jeremiah 31:3","The LORD appeared to us in the past, saying: 'I have loved you with an everlasting love; I have drawn you with unfailing kindness.'"],
  ["Hebrews 6:19","We have this hope as an anchor for the soul, firm and secure."],
  ["Psalm 119:9","How can a young person stay on the path of purity? By living according to your word."],
  ["Mark 9:23","'If you can?' said Jesus. 'Everything is possible for one who believes.'"],
  ["Psalm 55:22","Cast your cares on the LORD and he will sustain you; he will never let the righteous be shaken."],
  ["2 Peter 1:3","His divine power has given us everything we need for a godly life through our knowledge of him who called us by his own glory and goodness."],
  ["Proverbs 16:18","Pride goes before destruction, a haughty spirit before a fall."],
  ["1 Timothy 1:15","Here is a trustworthy saying that deserves full acceptance: Christ Jesus came into the world to save sinners — of whom I am the worst."],
  ["Romans 3:23-24","For all have sinned and fall short of the glory of God, and all are justified freely by his grace through the redemption that came by Christ Jesus."],
  ["Micah 6:8","He has shown you, O mortal, what is good. And what does the LORD require of you? To act justly and to love mercy and to walk humbly with your God."],
  ["John 14:1","Do not let your hearts be troubled. You believe in God; believe also in me."],
  ["Isaiah 55:8-9","'For my thoughts are not your thoughts, neither are your ways my ways,' declares the LORD. 'As the heavens are higher than the earth, so are my ways higher than your ways and my thoughts than your thoughts.'"],
  ["2 Timothy 3:16-17","All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness, so that the servant of God may be thoroughly equipped for every good work."],
  ["Psalm 147:3","He heals the brokenhearted and binds up their wounds."],
  ["Matthew 18:20","For where two or three gather in my name, there am I with them."],
  ["Isaiah 26:3","You will keep in perfect peace those whose minds are steadfast, because they trust in you."],
  ["John 5:24","Very truly I tell you, whoever hears my word and believes him who sent me has eternal life and will not be judged but has crossed over from death to life."],
  ["Isaiah 40:31","But those who hope in the LORD will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint."],
  ["Romans 12:18","If it is possible, as far as it depends on you, live at peace with everyone."],
  ["Job 19:25","I know that my redeemer lives, and that in the end he will stand on the earth."],
  ["Romans 5:1","Therefore, since we have been justified through faith, we have peace with God through our Lord Jesus Christ."],
  ["Deuteronomy 31:6","Be strong and courageous. Do not be afraid or terrified because of them, for the LORD your God goes with you; he will never leave you nor forsake you."],
  ["2 Thessalonians 3:3","But the Lord is faithful, and he will strengthen you and protect you from the evil one."],
  ["Ezekiel 36:26","I will give you a new heart and put a new spirit in you; I will remove from you your heart of stone and give you a heart of flesh."],
  ["Matthew 24:35","Heaven and earth will pass away, but my words will never pass away."],
  ["1 Corinthians 6:19-20","Do you not know that your bodies are temples of the Holy Spirit, who is in you, whom you have received from God? You are not your own; you were bought at a price."],
  ["Deuteronomy 7:9","Know therefore that the LORD your God is God; he is the faithful God, keeping his covenant of love to a thousand generations of those who love him and keep his commandments."],
  ["Luke 1:45","Blessed is she who has believed that the Lord would fulfill his promises to her!"],
  ["Isaiah 54:10","Though the mountains be shaken and the hills be removed, yet my unfailing love for you will not be shaken nor my covenant of peace be removed, says the LORD, who has compassion on you."],
  ["Colossians 3:17","And whatever you do, whether in word or deed, do it all in the name of the Lord Jesus, giving thanks to God the Father through him."],
  ["Psalm 40:1-2","I waited patiently for the LORD; he turned to me and heard my cry. He lifted me out of the slimy pit, out of the mud and mire; he set my feet on a rock and gave me a firm place to stand."],
  ["Ephesians 2:4-5","But because of his great love for us, God, who is rich in mercy, made us alive with Christ even when we were dead in transgressions — it is by grace you have been saved."],
  ["Daniel 3:17-18","If we are thrown into the blazing furnace, the God we serve is able to deliver us from it, and he will deliver us from Your Majesty's hand. But even if he does not, we want you to know that we will not serve your gods."],
  ["Matthew 6:33","But seek first his kingdom and his righteousness, and all these things will be given to you as well."],
  ["Joshua 24:15","But as for me and my household, we will serve the LORD."],
  ["Acts 1:8","But you will receive power when the Holy Spirit comes on you; and you will be my witnesses in Jerusalem, and in all Judea and Samaria, and to the ends of the earth."],
  ["Proverbs 1:7","The fear of the LORD is the beginning of wisdom, but fools despise wisdom and instruction."],
  ["Romans 12:1","Therefore, I urge you, brothers and sisters, in view of God's mercy, to offer your bodies as a living sacrifice, holy and pleasing to God — this is your true and proper worship."],
  ["Psalm 42:5","Why, my soul, are you downcast? Why so disturbed within me? Put your hope in God, for I will yet praise him, my Savior and my God."],
  ["Romans 12:12","Be joyful in hope, patient in affliction, faithful in prayer."],
  ["Mark 8:36","What good is it for someone to gain the whole world, yet forfeit their soul?"],
  ["Proverbs 27:17","As iron sharpens iron, so one person sharpens another."],
  ["1 Corinthians 10:13","No temptation has overtaken you except what is common to mankind. And God is faithful; he will not let you be tempted beyond what you can bear."],
  ["Genesis 1:27","So God created mankind in his own image, in the image of God he created them; male and female he created them."],
  ["1 John 1:9","If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness."],
  ["Psalm 100:4-5","Enter his gates with thanksgiving and his courts with praise; give thanks to him and praise his name. For the LORD is good and his love endures forever; his faithfulness continues through all generations."],
  ["1 John 5:14-15","This is the confidence we have in approaching God: that if we ask anything according to his will, he hears us. And if we know that he hears us — whatever we ask — we know that we have what we asked of him."],
  ["Numbers 6:24-26","The LORD bless you and keep you; the LORD make his face shine on you and be gracious to you; the LORD turn his face toward you and give you peace."],
  ["Romans 10:13","For, 'Everyone who calls on the name of the Lord will be saved.'"],
  ["Hosea 6:3","Let us acknowledge the LORD; let us press on to acknowledge him. As surely as the sun rises, he will appear; he will come to us like the winter rains, like the spring rains that water the earth."],
  ["2 Peter 3:9","The Lord is not slow in keeping his promise, as some understand slowness. Instead he is patient with you, not wanting anyone to perish, but everyone to come to repentance."],
  ["Psalm 121:1-2","I lift up my eyes to the mountains — where does my help come from? My help comes from the LORD, the Maker of heaven and earth."],
  ["Luke 12:32","Do not be afraid, little flock, for your Father has been pleased to give you the kingdom."],
  ["Isaiah 40:28-29","Do you not know? Have you not heard? The LORD is the everlasting God, the Creator of the ends of the earth. He will not grow tired or weary, and his understanding no one can fathom. He gives strength to the weary and increases the power of the weak."],
  ["Revelation 22:20","He who testifies to these things says, 'Yes, I am coming soon.' Amen. Come, Lord Jesus."],
  ["Malachi 3:10","Bring the whole tithe into the storehouse, that there may be food in my house. Test me in this, says the LORD Almighty, and see if I will not throw open the floodgates of heaven and pour out so much blessing that there will not be room enough to store it."],
  ["Romans 10:17","Consequently, faith comes from hearing the message, and the message is heard through the word about Christ."],
  ["1 John 4:4","You, dear children, are from God and have overcome them, because the one who is in you is greater than the one who is in the world."],
  ["Psalm 68:19","Praise be to the Lord, to God our Savior, who daily bears our burdens."],
  ["Luke 15:10","In the same way, I tell you, there is rejoicing in the presence of the angels of God over one sinner who repents."],
  ["1 Samuel 16:7","The LORD does not look at the things people look at. People look at the outward appearance, but the LORD looks at the heart."],
  ["Matthew 5:3","Blessed are the poor in spirit, for theirs is the kingdom of heaven."],
  ["Psalm 139:13-14","For you created my inmost being; you knit me together in my mother's womb. I praise you because I am fearfully and wonderfully made."],
  ["Acts 16:31","They replied, 'Believe in the Lord Jesus, and you will be saved — you and your household.'"],
  ["Lamentations 3:25","The LORD is good to those whose hope is in him, to the one who seeks him."],
  ["Hebrews 4:12","For the word of God is alive and active. Sharper than any double-edged sword, it penetrates even to dividing soul and spirit, joints and marrow; it judges the thoughts and attitudes of the heart."],
  ["Psalm 31:24","Be strong and take heart, all you who hope in the LORD."],
  ["Galatians 6:7","Do not be deceived: God cannot be mocked. A man reaps what he sows."],
  ["Isaiah 30:21","Whether you turn to the right or to the left, your ears will hear a voice behind you, saying, 'This is the way; walk in it.'"],
  ["John 11:25-26","Jesus said to her, 'I am the resurrection and the life. The one who believes in me will live, even though they die; and whoever lives by believing in me will never die.'"],
  ["Psalm 25:4-5","Show me your ways, LORD, teach me your paths. Guide me in your truth and teach me, for you are God my Savior, and my hope is in you all day long."],
  ["2 Corinthians 5:7","For we live by faith, not by sight."],
  ["1 John 4:18","There is no fear in love. But perfect love drives out fear, because fear has to do with punishment. The one who fears is not made perfect in love."],
  ["Psalm 46:10","He says, 'Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth.'"],
  ["James 4:7","Submit yourselves, then, to God. Resist the devil, and he will flee from you."],
  ["Proverbs 16:3","Commit to the LORD whatever you do, and he will establish your plans."],
  ["John 6:35","Then Jesus declared, 'I am the bread of life. Whoever comes to me will never go hungry, and whoever believes in me will never be thirsty.'"],
  ["Proverbs 4:23","Above all else, guard your heart, for everything you do flows from it."],
  ["1 Timothy 4:12","Don't let anyone look down on you because you are young, but set an example for the believers in speech, in conduct, in love, in faith and in purity."],
  ["Psalm 51:10","Create in me a pure heart, O God, and renew a steadfast spirit within me."],
  ["Revelation 21:5","He who was seated on the throne said, 'I am making everything new!' Then he said, 'Write this down, for these words are trustworthy and true.'"],
  ["Joel 2:32","And everyone who calls on the name of the LORD will be saved."],
  ["Hebrews 10:25","Not giving up meeting together, as some are in the habit of doing, but encouraging one another — and all the more as you see the Day approaching."],
  ["Proverbs 27:1","Do not boast about tomorrow, for you do not know what a day may bring."],
  ["Philippians 4:6-7","Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus."],
  ["Psalm 138:3","When I called, you answered me; you greatly emboldened me."],
  ["John 14:6","Jesus answered, 'I am the way and the truth and the life. No one comes to the Father except through me.'"],
  ["Isaiah 43:18-19","Forget the former things; do not dwell on the past. See, I am doing a new thing! Now it springs up; do you not perceive it?"],
  ["John 10:27-28","My sheep listen to my voice; I know them, and they follow me. I give them eternal life, and they shall never perish; no one will snatch them out of my hand."],
  ["Mark 1:15","'The time has come,' he said. 'The kingdom of God has come near. Repent and believe the good news!'"],
  ["Job 1:21","The LORD gave and the LORD has taken away; may the name of the LORD be praised."],
  ["Matthew 5:9","Blessed are the peacemakers, for they will be called children of God."],
  ["Jeremiah 1:5","Before I formed you in the womb I knew you, before you were born I set you apart; I appointed you as a prophet to the nations."],
  ["Matthew 5:14","You are the light of the world. A town built on a hill cannot be hidden."],
  ["Isaiah 61:1","The Spirit of the Sovereign LORD is on me, because the LORD has anointed me to proclaim good news to the poor."],
  ["2 Corinthians 5:17","Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!"],
  ["Proverbs 15:1","A gentle answer turns away wrath, but a harsh word stirs up anger."],
  ["Hebrews 4:15-16","For we do not have a high priest who is unable to empathize with our weaknesses, but we have one who has been tempted in every way, just as we are — yet he did not sin. Let us then approach God's throne of grace with confidence."],
  ["Psalm 90:12","Teach us to number our days, that we may gain a heart of wisdom."],
  ["Matthew 28:19-20","Therefore go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit, and teaching them to obey everything I have commanded you."],
  ["1 Chronicles 16:11","Look to the LORD and his strength; seek his face always."],
  ["1 Thessalonians 5:11","Therefore encourage one another and build each other up, just as in fact you are doing."],
  ["Psalm 19:14","May these words of my mouth and this meditation of my heart be pleasing in your sight, LORD, my Rock and my Redeemer."],
  ["1 Peter 5:6-7","Humble yourselves, therefore, under God's mighty hand, that he may lift you up in due time. Cast all your anxiety on him because he cares for you."],
  ["Mark 10:27","Jesus looked at them and said, 'With man this is impossible, but not with God; all things are possible with God.'"],
  ["Psalm 90:2","Before the mountains were born or you brought forth the whole world, from everlasting to everlasting you are God."],
  ["Luke 6:38","Give, and it will be given to you. A good measure, pressed down, shaken together and running over, will be poured into your lap."],
  ["Psalm 62:1-2","Truly my soul finds rest in God; my salvation comes from him. Truly he is my rock and my salvation; he is my fortress, I will never be shaken."],
  ["John 13:34-35","A new command I give you: Love one another. As I have loved you, so you must love one another. By this everyone will know that you are my disciples, if you love one another."],
  ["Psalm 34:8","Taste and see that the LORD is good; blessed is the one who takes refuge in him."],
  ["John 15:5","I am the vine; you are the branches. If you remain in me and I in you, you will bear much fruit; apart from me you can do nothing."],
  ["Habakkuk 2:4","But the righteous person will live by his faithfulness."],
  ["Acts 4:12","Salvation is found in no one else, for there is no other name under heaven given to mankind by which we must be saved."],
  ["Psalm 42:1-2","As the deer pants for streams of water, so my soul pants for you, my God. My soul thirsts for God, for the living God."],
  ["Revelation 4:11","You are worthy, our Lord and God, to receive glory and honor and power, for you created all things, and by your will they were created and have their being."],
  ["Proverbs 13:20","Walk with the wise and become wise, for a companion of fools suffers harm."],
  ["Matthew 5:8","Blessed are the pure in heart, for they will see God."],
  ["Proverbs 18:10","The name of the LORD is a fortified tower; the righteous run to it and are safe."],
  ["Mark 11:24","Therefore I tell you, whatever you ask for in prayer, believe that you have received it, and it will be yours."],
  ["James 1:17","Every good and perfect gift is from above, coming down from the Father of the heavenly lights, who does not change like shifting shadows."],
];

// Returns verse based on Eastern Time day-of-year, rotating daily at midnight ET
export function getTodaysVerse() {
  const now = new Date();
  const eastern = new Date(now.toLocaleString("en-US", { timeZone: "America/New_York" }));
  const start = new Date(eastern.getFullYear(), 0, 0);
  const dayOfYear = Math.floor((eastern - start) / 86400000);
  const idx = (dayOfYear - 1 + VERSES.length) % VERSES.length;
  return { reference: VERSES[idx][0], text: VERSES[idx][1] };
}